trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

variables:
  javaVersion: '17'
  imageRepository: 'fulfilment-monolith'
  dockerfilePath: 'src/main/docker/Dockerfile.jvm'

  # Azure Container Registry service connection
  dockerRegistryServiceConnection: 'acr-service-connection'
  containerRegistry: 'myacr.azurecr.io'

  tag: '$(Build.BuildId)'

stages:
  # We can add the stage to scan repository with checksum
  # ============================================================
  # BUILD
  # ============================================================
  - stage: Build
    displayName: Build

    jobs:
      - job: Build
        displayName: Compile Application

        pool:
          vmImage: ubuntu-latest

        steps:

          - checkout: self

          - task: Cache@2
            displayName: Cache Maven Repository
            inputs:
              key: 'maven | "$(Agent.OS)" | **/pom.xml'
              restoreKeys: |
                maven | "$(Agent.OS)"
              path: ~/.m2/repository

          - task: JavaToolInstaller@0
            inputs:
              versionSpec: '$(javaVersion)'
              jdkArchitectureOption: x64
              jdkSourceOption: PreInstalled

          - task: Maven@4
            displayName: Compile
            inputs:
              mavenPomFile: pom.xml
              goals: clean compile
              javaHomeOption: JDKVersion
              jdkVersionOption: '1.17'

  # ============================================================
  # UNIT TESTS AND COVERAGE
  # ============================================================
  - stage: UnitTests
    displayName: Unit Tests And Coverage
    dependsOn: Build

    jobs:
      - job: UnitTests

        pool:
          vmImage: ubuntu-latest
        services:
          postgres:
            image: postgres:16
            ports:
              - 15432:5432
            env:
              POSTGRES_DB: quarkus_test
              POSTGRES_USER: quarkus_test
              POSTGRES_PASSWORD: quarkus_test
        steps:
          - checkout: self
          - bash: |
              echo "Waiting for PostgreSQL..."
              sleep 10
            displayName: Wait for PostgreSQL
          - task: Maven@4
            displayName: Run Unit Tests
            inputs:
              mavenPomFile: pom.xml
              goals: test
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              javaHomeOption: JDKVersion
              jdkVersionOption: '1.17'

          - task: PublishTestResults@2
            inputs:
              testResultsFormat: JUnit
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              failTaskOnFailedTests: true

          - task: PublishCodeCoverageResults@2
            displayName: 'Publish JaCoCo Coverage'
            inputs:
              codeCoverageTool: 'JaCoCo'
              summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/target/site/jacoco/jacoco.xml'
              reportDirectory: '$(System.DefaultWorkingDirectory)/**/target/site/jacoco'
              failIfCoverageEmpty: true
          - task: PublishPipelineArtifact@1
            displayName: 'Publish JaCoCo HTML Report'
            inputs:
              targetPath: '$(System.DefaultWorkingDirectory)/target/site/jacoco'
              artifact: 'jacoco-report'
          # ============================================================
  # INTEGRATION TESTS
  # ============================================================
  - stage: IntegrationTests
    displayName: Integration Tests
    dependsOn: UnitTests

    jobs:
      - job: IntegrationTests

        pool:
          vmImage: ubuntu-latest
        services:
          postgres:
            image: postgres:16
            ports:
              - 15432:5432
            env:
              POSTGRES_DB: quarkus_test
              POSTGRES_USER: quarkus_test
              POSTGRES_PASSWORD: quarkus_test
        steps:
          - checkout: self
          - bash: |
              echo "Waiting for PostgreSQL..."
              sleep 10
            displayName: Wait for PostgreSQL
          - task: Maven@4
            displayName: Run Integration Tests
            inputs:
              mavenPomFile: pom.xml
              goals: verify
              publishJUnitResults: true
              testResultsFiles: |
                **/failsafe-reports/TEST-*.xml
                **/surefire-reports/TEST-*.xml
              javaHomeOption: JDKVersion
              jdkVersionOption: '1.17'

          - task: PublishTestResults@2
            inputs:
              testResultsFormat: JUnit
              testResultsFiles: |
                **/failsafe-reports/TEST-*.xml
                **/surefire-reports/TEST-*.xml
              failTaskOnFailedTests: true

  # ============================================================
  # PACKAGE
  # ============================================================
  - stage: Package
    displayName: Package
    dependsOn: IntegrationTests

    jobs:
      - job: Package

        pool:
          vmImage: ubuntu-latest

        steps:

          - checkout: self

          - task: Maven@4
            displayName: Package Quarkus App
            inputs:
              mavenPomFile: pom.xml
              goals: package -DskipTests
              javaHomeOption: JDKVersion
              jdkVersionOption: '1.17'

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: target
              ArtifactName: quarkus-build

  # ============================================================
  # DOCKER BUILD
  # ============================================================
  - stage: Docker
    displayName: Docker Build & Push
    dependsOn: Package

    jobs:
      - job: Docker

        pool:
          vmImage: ubuntu-latest

        steps:

          - checkout: self

          - task: Docker@2
            displayName: Build and Push Image
            inputs:
              command: buildAndPush
              repository: $(imageRepository)
              dockerfile: $(dockerfilePath)
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                latest
                $(tag)

  # ============================================================
  # DEPLOY TO STAGING
  # ============================================================
  - stage: Deploy_Staging
    displayName: Deploy to Staging
    dependsOn: Docker

    jobs:

      - deployment: DeployStaging

        environment: staging

        strategy:
          runOnce:

            deploy:

              steps:

                - script: |
                    echo "Deploying image $(tag) to STAGING"
                  displayName: Deploy

  # ============================================================
  # HEALTH CHECK
  # ============================================================
  - stage: HealthCheck
    displayName: Health Check
    dependsOn: Deploy_Staging

    jobs:

      - job: HealthCheck

        pool:
          vmImage: ubuntu-latest

        steps:

          - bash: |
              
              echo "Waiting for application startup..."
              
              sleep 30
              
              curl --fail \
                http://staging.mycompany.com/q/health

            displayName: Quarkus Health Check

  # ============================================================
  # DEPLOY TO PRODUCTION
  # ============================================================
  - stage: Deploy_Production
    displayName: Deploy to Production

    dependsOn: HealthCheck

    jobs:
      - deployment: Production
        environment: production
        strategy:
          runOnce:

            deploy:

              steps:

                - script: |
                    echo "Deploying image $(tag) to PRODUCTION"
                  displayName: Deploy Production

  # ============================================================
  # PRODUCTION HEALTH CHECK
  # ============================================================
  - stage: ProductionHealthCheck
    displayName: Production Health Check

    dependsOn: Deploy_Production

    jobs:

      - job: HealthCheck

        pool:
          vmImage: ubuntu-latest

        steps:

          - bash: |
              
              sleep 30
              
              curl --fail \
                http://prod.monolith.com/q/health

            displayName: Verify Production Health

  # ============================================================
  # ROLLBACK
  # ============================================================
  - stage: Rollback

    displayName: Rollback

    dependsOn: ProductionHealthCheck

    condition: failed()

    jobs:

      - job: Rollback

        pool:
          vmImage: ubuntu-latest

        steps:

          - script: |
              
              echo "Production health check failed."
              
              echo "Rolling back to previous version..."
              
              # Example:
              # kubectl rollout undo deployment/fulfilment-monolith

            displayName: Rollback Deployment